name: build
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]
runs-on: ${{ matrix.os }}

strategy:
  matrix:
    os: [ubuntu-16.04, ubuntu-18.04]

jobs:
  build:
    name: make
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: make
      

