name: build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: make
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: make
      

