name: Module Compiles
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Compile
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      
      - name: Compile
        run: ls
      

